### ISSUE TITLE
bad or invalid `--board` flags cause silent failures that look like success (?)

### ISSUE THREAD

**Issue by ppannuto** [helena-project/tockloader#13]
not thoroughly debugged: https://bot.tockos.org/tockbot/tock/2017-07-07/?msg=12759&page=1

**Comment by bradjc** [comment]
So tockloader doesn't really care about which board you are programming, all it really needs to know is the architecture (to know which binary to install) or the `jtag-device` for JLinkExe of the main MCU.

`--board` (or the bootloader attribute on the hw itself) is intended to be a hint so that tockloader can verify that the application TAB you are trying to install was intended for your board or not. However, none of our current apps specify compatible boards (and thus say they work with all boards), and therefore this option doesn't have any noticeable effect. If an app did specify compatible boards, and the board to be programmed wasn't one of them, tockloader would throw an error and make you use --force to program the board.
